name: Validate with hassfest

on:
  push:

jobs:
  validate:
    runs-on: "ubuntu-latest"
    steps:
        - uses: "actions/checkout@v4"
        - name: Validate with hassfest
          run: |
                  python3 -m pip install --upgrade pip
                  pip install homeassistant-hassfest
                  hassfest . --allow-domain-mismatch
