name: Validate with hassfest

on:
  pull_request:
  push:

jobs:
  validate:
    runs-on: "ubuntu-latest"
    steps:
        - uses: "actions/checkout@v4"
        - uses: "home-assistant/actions/hassfest@master"
          env:
          HASSFEST_CONTENT_IN_ROOT: "true"
